### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by krprashant94** [oishikm/numc#1]
As you aware C/C++ does not have automatic garbage collectorer like java. People like me, might use this project for handeling big data and end up with losing 5-10GB of coustly SSD storage in memory leak.
 
You might achieve garbage collection by using class and object. A possible way is to keep track of pointer reference in class member and in destructor of class `free(ref[0]);`

**Comment by oishikm** [comment]
This project was made solely for C, hence there is no ```class``` as C is not an OOP language. Using classes would make numc unusable in C. However your point is very good, I will see if I can make any garbage collector using ```struct```. For now you can manually free any dynamically allocated memory in main.c, I will try to put in a simple de-allocation in the next commit.  

If you wish to use something similar to numc in C++ with class/object, you can also check out [this](https://github.com/dpilger26/NumCpp) awesome project by David Pilger.

**Comment by oishikm** [comment]
Added function for garbage collection:
https://github.com/oishikm/numc/blob/fe67d573f1ceef79c6bac70d585898fa3337bba9/numc.h#L17
